config/routes.rb
Rails.application.routes.draw do
  # get 'movie_sets/index'
  # get 'movie_sets/show'
  devise_for :users
  root to: 'pages#home'
  resources :movie_sets, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :movie_set
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, inclusion: { in: %w(upcoming past) }
end

app/models/movie_set.rb
class MovieSet < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
  validates :title, presence: true
  validates :description, presence: true
  validates :media_name, presence: true
  validates :address, presence: true
  geocoded_by :address
  validates :price_per_day, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :movie_sets
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /\b[\w.-]+@[\w.-]+\.\w{2,4}\b/, message: "Please add a valid email" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    # @user = current_user
    # @booking.user = @user
    #     const end_date = new Date(string_end_date.value);
    # const start_milliseconds = start_date.getTime();
    # const end_milliseconds = end_date.getTime();
    # const milliseconds = end_milliseconds - start_milliseconds;
    # const period = milliseconds/86400000;
    # const totalcalculation = period * price_per_day.innerText
    @booking.movie_set = MovieSet.find(params[:movie_set_id].to_i)
    @price_per_day = @booking.movie_set.price_per_day
    @end_date = params[:booking][:end_date].to_date
    @start_date = params[:booking][:start_date].to_date
    @total_price = ((@end_date - @start_date) * @price_per_day).to_i
    @booking.total_price = @total_price
    if @booking.save!
      redirect_to dashboard_path
    else
      redirect_to movie_set_path(params[:movie_set_id].to_i)
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :status)
  end
end

app/controllers/movie_sets_controller.rb
class MovieSetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:search]
      @search = params[:search][:query]
      @title = ""
      @movie_sets = MovieSet.where("title ILIKE ? OR media_name ILIKE ? OR address ILIKE ?", "%#{@search}%", "%#{@search}%", "%#{@search}%")
    else
      @movie_sets = MovieSet.geocoded
    end

    @markers = @movie_sets.map do |movie|
      {
        lat: movie.latitude,
        lng: movie.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { movie_set: movie })
      }
    end
  end

  def show
    @movie_set = MovieSet.find(params[:id])
    @booking = Booking.new
  end

  def new
    @movie_set = MovieSet.new(params[:movie_set])
  end

  def create
    @movie_set = MovieSet.new(movie_set_params)
    @movie_set.user_id = current_user.id
    @movie_set.save
    redirect_to movie_set_path(@movie_set), alert: "You added a new show!"
  end

  def edit
    @movie_set = MovieSet.find(params[:id])
  end

  def update
    @movie_set = MovieSet.find(params[:id])
    @movie_set.update(movie_set_params)
    redirect_to movie_set_path(@movie_set)
  end

  def destroy
    @movie_set = MovieSet.find(params[:id])
    @movie_set.destroy
    redirect_to dashboard_path
  end

  private

  def movie_set_params
    params.require(:movie_set).permit(:title, :address, :description, :media_name, :price_per_day, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @user = current_user
    @bookings = @user.bookings
    @movie_sets = MovieSet.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Live your set : live the greatest experiences</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/notice' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/movie_sets/_info_window.html.erb
<%= link_to movie_set_path(movie_set) do %>
<h2><%= movie_set.title %></h2>
  <%= cl_image_tag(movie_set.photos.first.key, :width=>220, :height=>200, :crop=>"fill") %>
<p><em><%= movie_set.address %></em></p>
<% end %>

app/views/movie_sets/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-new">
      <div class="header">
        <h2>Hello <%= current_user.first_name %></h2>
        <p>Please edit your set:</p>
      </div>
      <div class="new-set">
        <%= render 'shared/form', movie_set: @movie_set %>
      </div>
    </div>
  </div>
</div>

app/views/movie_sets/index.html.erb
<div class="container">
  <div class="search-index">
    <%= render 'shared/search' %>
  </div>
  <div class="results">
    <p>You have <strong><%= @movie_sets.count %></strong> results</p>
  </div>
  <div class="content">
    <div class="cards">
      <% @movie_sets.each do |movie_set| %>
        <div class="card-trip">
            <%= link_to movie_set_path(movie_set, query: @search) do %>
            <%= cl_image_tag movie_set.photos.first.key, class: "card-trip-img" %>
            <% end %>
          <div class="card-trip-infos">
            <h2><%= movie_set.title %></h2>
            <p><%= movie_set.address %></p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="map">
      <div
        id="map"
        style="width: 100%;
        height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
  </div>
</div>

app/views/movie_sets/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-new">
      <div class="header">
        <h2>Hello <%= current_user.first_name %></h2>
        <p>Please add a new movie set:</p>
      </div>
      <div class="new-set">
        <%= render 'shared/form', movie_set: @movie_set %>
      </div>
    </div>
  </div>
</div>

app/views/movie_sets/show.html.erb
<div id="carousel">
    <div id="carousel-show-movie-set" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% @movie_set.photos.each do |photo|%>
          <div class="carousel-item <%= "active" if photo == @movie_set.photos.first %>">
            <%= cl_image_tag photo.key, class: "d-block w-100", style:"height: 350px"%>
          </div>
        <% end %>
      </div>
    <a class="carousel-control-prev" href="#carousel-show-movie-set" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-show-movie-set" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="better-container">
  <div class="row">
    <div class="col-8">
      <div id="show-movie-set-title">
        <h1><%= @movie_set.title.capitalize %></h1>
      </div>
      <div id="show-movie-set-media-name">
        <p><i class="fas fa-film"></i><%=  @movie_set.media_name %></p>
      </div>
      <div id="show-movie-set-address">
        <p><i class="fas fa-map-marked-alt"></i><%=  @movie_set.address %></p>
      </div>
      <div class="container box-icon">
        <div class="card description-card">
          <i class="fas fa-user-friends description-icon"></i>
          <p>max 1500 people</p>
        </div>
        <div class="card description-card">
          <i class="fas fa-ruler-combined description-icon"></i>
          <p>3000 square meters</p>
        </div>
        <div class="card description-card">
          <i class="fas fa-parking description-icon"></i>
          <p>Free parking</p>
        </div>
      </div>
      <div id="show-movie-set-description">
        <h5>Description</h5>
        <p><%= @movie_set.description %></p>
        <p><%= link_to '<i class="fas fa-arrow-left"></i>Back to the results'.html_safe, movie_sets_path %></p>
      </div>
    </div>
    <% unless current_user == @movie_set.user %>
      <div class="col-4">
        <div class="card booking-card">
          <div class="booking-card-item booking-card-price-per-day">
            <strong><span id="price-per-day"><%= @movie_set.price_per_day %></span>$ / day</strong>
              <%= simple_form_for [@movie_set, @booking] do |f| %>
                <%= f.input :start_date, as: :string, required: false, placeholder: "From when?", input_html: {class: "datepicker", id:"start-date"} %>
                <%= f.input :end_date, as: :string, required: false, placeholder: "To when?", input_html: {class: "datepicker", id:"end-date"} %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :status, value: "upcoming" %>
                  <div class="booking-card-total-price">
                    <p><strong>Total Price: <span id="total-price"></span>$</strong></p>
                  </div>
                <%= f.submit "Book", class: "btn btn-flat btn-review" %>
              <% end %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="main">
    <h2>Hello <%= current_user.first_name %></h2>
    <p>Welcome to your dashboard, please see below the list of your marvellous sets, and all your past and upcoming bookings in our platform.</p>
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active tab-link-custom" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">My movie sets</a>
      </li>
      <li class="nav-item">
        <a class="nav-link tab-link-custom" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">My booking</a>
      </li>
      <hr />
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <div class="line">
          <div class="movies">
             <% @movie_sets.each do |m| %>
              <div class="card" style="width: 18rem;">
                <%= link_to movie_set_path(m) do %>
                 <%= cl_image_tag m.photos.first.key, class: "card-img-top" %>
                  <div class="card-body">
                    <h5 class="card-title"><%= m.title %></h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                <% end %>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item"><i class="fas fa-film"></i><%= m.media_name %></li>
                  <li class="list-group-item"><i class="fas fa-map-marked-alt"></i><%= m.address %></li>
                  <li class="list-group-item">Ratings : <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i></li>
                </ul>
                <div class="card-body">
                  <p><%= link_to edit_movie_set_path(m), class:"card-link" do %>
                    <i class="fas fa-edit"></i>Update the set
                  <% end %></p>
                  <p><%= link_to movie_set_path(m), class:"card-link", method: :delete, data: { confirm: "Are you sure?"} do %>
                    <i class="fas fa-trash-alt"></i>Delete the set
                  <% end %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
    </div>
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
          <div class="line">
            <div class="movies">
              <% @bookings.each do |booking| %>
                <% if booking.status == "upcoming" %>
                  <div class="card" style="width: 18rem;">
                  <div class="status" style="position: absolute; border-radius: 4px; margin-top: -7px;">
                    <span class="badge badge-secondary"><%= booking.status %></span>
                  </div>
                    <%= cl_image_tag booking.movie_set.photos.first.key, class: "card-img-top", style: "background: linear-gradient(rgba(230,230,230,0.1), rgba(230,230,230,0.1))"%>
                    <div class="card-body">
                      <h5 class="card-title"><%= booking.movie_set.title %></h5>
                      <p class="card-text py-3">Here are the details concerning your reservation.</p>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"><i class="fas fa-film"></i><strong><%= booking.start_date %> <span> - </span> <%= booking.end_date %></strong></li>
                      <li class="list-group-item"><i class="fas fa-coins pr-3"></i><strong><%= booking.total_price %><span> $ </span></strong></li>
                    </ul>
                  </div>
                </div>
              <% else %>
                <div class="card" style="width: 18rem; background: rgb(230, 230, 230);">
                <div class="status" style="position: absolute; border-radius: 4px; margin-top: -7px;">
                  <span class="badge badge-primary"><%= booking.status %></span>
                </div>
                  <%= cl_image_tag booking.movie_set.photos.first.key, class: "card-img-top", style: "background: linear-gradient(rgba(230,230,230,0.1), rgba(230,230,230,0.1))"%>
                  <div class="card-body">
                    <h5 class="card-title"><%= booking.movie_set.title %></h5>
                    <p class="card-text py-3">Here are the details concerning your reservation.</p>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item" style="background: rgb(230, 230, 230);"><i class="fas fa-film"></i><strong><%= booking.start_date %> <span> - </span> <%= booking.end_date %></strong></li>
                    <li class="list-group-item" style="background: rgb(230, 230, 230);"><i class="fas fa-coins pr-3"></i><strong><%= booking.total_price %><span> $ </span></strong></li>
                  </ul>
                </div>
              </div>
              <% end %>
            </div>
          </div>
      </div>
    <% end %>
    </div>
  </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(35,53,103,0.4)), url(https://images.unsplash.com/photo-1485846234645-a62644f84728?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1340&q=80);">
  <div class="container">
    <h1>Immerse yourself in the film or TV show of your choice</h1>
    <p>Live again the greatest scenes of your life!</p>
    <div class="search-box">
        <%= simple_form_for :search, url: movie_sets_path, method: :get do |f| %>
      <div class="search-form-control form-group" style="position: absolute; width:445px; margin-top: -10px;">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Type your movie, series or location" style="padding: 0px 20px; font-size: 17px; font-style: italic" />
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i> Search
        </button>
      </div>
  <% end %>
    </div>
  </div>
</div>
<div class="main">
    <div class="divider">
      <h2>LIVE</h2>
      <p><em>your set</em></p>
    </div>
    <div class="card-deck">
      <div class="card">
        <img class="card-img-top" src="https://res.cloudinary.com/ddlesqeup/image/upload/v1574110334/step1.svg" alt="Card image cap">
        <div class="card-body">
          <div class="flag-1">
            <span>1</span>
          </div>
          <h5 class="card-title">Browse our list of sets</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Powered with 💗 from 321</small>
        </div>
      </div>
      <div class="card">
        <img class="card-img-top" src="https://res.cloudinary.com/ddlesqeup/image/upload/v1574110334/step2.svg" alt="Card image cap">
        <div class="card-body">
          <div class="flag-2">
            <span>2</span>
          </div>
          <h5 class="card-title">Select the set of your dreams</h5>
          <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Powered with 💗 from 321</small>
        </div>
      </div>
      <div class="card">
        <img class="card-img-top" src="https://res.cloudinary.com/ddlesqeup/image/upload/v1574110334/step3.svg" alt="Card image cap">
        <div class="card-body">
          <div class="flag-3">
            <span>3</span>
          </div>
          <h5 class="card-title">Book it quickly and safely</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Powered with 💗 from 321</small>
        </div>
      </div>
    </div>
</div>

app/views/shared/_alert-show.html.erb
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading"><%= alert %></h4>
  <p>Aww yeah, you successfully created a new set ! This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
  <hr>
  <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
</div>

app/views/shared/_alertshow.html.erb
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong><%= alert %></strong> 🎉 you successfully signed in to our service.</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with 💗 at Le Wagon
  </div>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for @movie_set, defaults: { input_html: { class: 'form-row' } } do |f| %>
  <div class="set_details">
     <div class="bubble1">1</div>
       <h3>Your set</h3>
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { maxlength: 500 } %>
    <%= f.input :media_name %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>
  <div id="button-continue-container" class="button-continue">
    <%= link_to "Continue", {id: "continue-btn", class: "btn btn-primary"} %>
  </div>
  <div class="set_charact" style="display: none;">
      <div class="bubble2">2</div>
       <h3>Characteristics</h3>
    <%= f.input :address %>
    <%= f.input :price_per_day %>
    <%= f.button :submit, class: 'btn btn-primary', style:"margin-left: 14.5%" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if action_name == 'home' %>
  <div class="navbar navbar-expand-sm navbar-white navbar-light navbar-lewagon">
    <div class="container-hp">
      <div class="logo-typo">
        <%= link_to root_path, class: "navbar-brand" do %>
           <i class="fas fa-film white"></i>
           <h1 id="logo-white">Live your set</h1>
        <% end %>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <% if user_signed_in? %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to "Add a set", new_movie_set_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "My dashboard", dashboard_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <%= image_tag "https://res.cloudinary.com/ddlesqeup/image/upload/v1574436646/Capture_d_e%CC%81cran_2019-11-22_16.30.09_jukihj.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            </ul>
          </div>
        <% else %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container">
      <div class="logo-typo">
        <%= link_to root_path, class: "navbar-brand" do %>
           <i class="fas fa-film"></i>
           <h1 id="logo">Live your set</h1>
        <% end %>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <% if user_signed_in? %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to "Add a set", new_movie_set_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "My dashboard", dashboard_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <%= image_tag "https://res.cloudinary.com/ddlesqeup/image/upload/v1574436646/Capture_d_e%CC%81cran_2019-11-22_16.30.09_jukihj.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </li>
            </ul>
          </div>
        <% else %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_notice.html.erb
<p class="notice"><%= notice %></p>

<% if alert == "You added a new show!" %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><strong><%= alert %></strong> 🎉 you successfully signed in to our service.</span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% else %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/shared/_search.html.erb
<%= simple_form_for :search, url: movie_sets_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <% if params[:search] %>
      <input class="form-control string required" type="text" id="search_query" value="<%= params[:search][:query] %>" />
      <% else %>
      <input class="form-control string required" type="text" id="search_query" value=" <%= params[:query] %>" />
    <% end %>
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>